# This Dockerfile defines the base image for the ansible-operator image.
# It is built with dependencies that take a while to download, thus speeding
# up ansible deploy jobs.

FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.17 AS basebuilder

COPY . /go/src/github.com/openshift/ansible-operator-plugins
RUN cd /go/src/github.com/openshift/ansible-operator-plugins \
  && make build


FROM registry.ci.openshift.org/ocp/4.17:base-rhel9 as base
ARG TARGETARCH

# Install Rust so that we can ensure backwards compatibility with installing/building the cryptography wheel across all platforms
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustc --version


RUN mkdir -p /etc/ansible \
  && echo "localhost ansible_connection=local" > /etc/ansible/hosts \
  && echo '[defaults]' > /etc/ansible/ansible.cfg \
  && echo 'roles_path = /opt/ansible/roles' >> /etc/ansible/ansible.cfg \
  && echo 'library = /usr/share/ansible/openshift' >> /etc/ansible/ansible.cfg


# Copy python dependencies (including ansible) to be installed using Pipenv
COPY images/ansible-operator/Pipfile* ./

# Instruct pip(env) not to keep a cache of installed packages,
# to install into the global site-packages and
# to clear the pipenv cache as well
ENV PIP_NO_CACHE_DIR=1 \
   WORKON_HOME=/pipenv \
  #  PIPENV_SYSTEM=1 \
   PIPENV_CLEAR=1

RUN set -e && yum clean all && rm -rf /var/cache/yum/* \
  && yum update -y \
  #&& yum install -y libffi-devel openssl-devel python39-devel gcc python39-pip python39-setuptools \
  && yum install -y libffi-devel openssl-devel gcc python3-pip \
  && pip3 install --upgrade pip~=23.3.2 \
  && pip3 install pipenv==2023.11.15 \
  && pipenv install --deploy \
  # NOTE: This ignored vulnerability (70612) was detected in jinja2, \
  # but the vulnerability is disputed and may never be fixed. See: \
  #  - https://github.com/advisories/GHSA-f6pv-j8mr-w6rr \
  #  - https://github.com/dbt-labs/dbt-core/issues/10250 \
  #  - https://data.safetycli.com/v/70612/97c/ \
  # NOTE: This ignored vulnerability (71064) was detected in requests, \
  # but the upgraded version doesn't support the use case (protocol we are using).\
  # Ref: https://github.com/operator-framework/ansible-operator-plugins/pull/67#issuecomment-2189164688
  # && pipenv check --ignore 70612 --ignore 71064 \
  # && yum remove -y gcc libffi-devel openssl-devel python39-devel \
  && yum remove -y gcc libffi-devel openssl-devel \
  && yum clean all \
  && rm -rf /var/cache/yum 

# Hack to set up the Pipenv properly
RUN VENV=$(ls ${WORKON_HOME}) \
  && cp -r ${WORKON_HOME}/${VENV}/bin/* /usr/local/bin \
  && mkdir -p /usr/local/lib64/python3.9/site-packages \
  && mkdir -p /usr/local/lib/python3.9/site-packages \
  && cp -r ${WORKON_HOME}/${VENV}/lib64/python3.9/site-packages/* /usr/local/lib64/python3.9/site-packages \
  && cp -r ${WORKON_HOME}/${VENV}/lib/python3.9/site-packages/* /usr/local/lib/python3.9/site-packages

COPY --from=basebuilder /usr/local/bin /usr/local/bin

# Install TINI
ENV TINI_VERSION=v0.19.0
RUN curl -L -o /tini https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${TARGETARCH} \
  && chmod +x /tini && /tini --version

# Final image.
FROM base

ENV HOME=/opt/ansible \
    USER_NAME=ansible \
    USER_UID=1001

# Ensure directory permissions are properly set
RUN echo "${USER_NAME}:x:${USER_UID}:0:${USER_NAME} user:${HOME}:/sbin/nologin" >> /etc/passwd \
  && mkdir -p ${HOME}/.ansible/tmp \
  && chown -R ${USER_UID}:0 ${HOME} \
  && chmod -R ug+rwx ${HOME}

WORKDIR ${HOME}
USER ${USER_UID}

COPY --from=basebuilder /go/src/github.com/openshift/ansible-operator-plugins/ansible-operator /usr/local/bin/ansible-operator

ENTRYPOINT ["/tini", "--", "/usr/local/bin/ansible-operator", "run", "--watches-file=./watches.yaml"]