FROM registry.ci.openshift.org/ocp/4.21:base-rhel9

RUN set -e && dnf clean all && rm -rf /var/cache/dnf/* \
  && dnf update -y \
  && dnf install -y rust cargo libffi-devel python3.12-devel gcc \
  && pushd /usr/local/bin && ln -sf ../../bin/python3.12 python3 && popd \
  && python3 -m ensurepip --upgrade

COPY ./images/ansible-operator/Pipfile* ./

# Install pybuild-deps to generate build dependencies.
# This is recommended by Hermeto for generating requirements-build.txt
# that contains all build dependencies needed to build the project from source.
RUN python3 -m pip install pybuild-deps

# Pin pip to 24.0 to maintain compatibility with pybuild-deps.
# pip >= 24.1 changed the Downloader API (added resume_retries argument)
# which breaks pybuild-deps 0.5.0.
RUN python3 -m pip install pip==24.0

# Create requirements.in file from the pipenv created using the
# same Pipfile and Pipfile.lock used for upstream image. Then
# use pip-compile to generate the requirements.txt file.
RUN python3 -m pip install pipenv==2023.11.15 \
  && python3 -m pip install pip-tools \
  && pipenv install --deploy \
  && pipenv check \
  && pipenv run pip freeze --all  > ./requirements.in \
  # Pin python-dateutil to 2.9.0 (pipenv resolves to 2.9.0.post0 which is not available in OSBS)
  && sed -i 's/python-dateutil==2.9.0.post0/python-dateutil==2.9.0/' ./requirements.in \
  && pip-compile --output-file=./requirements.txt ./requirements.in --strip-extras --allow-unsafe \
  && pybuild-deps compile requirements.txt -o requirements-build.txt

VOLUME /tmp/requirements
ENTRYPOINT ["cp", "./requirements.txt", "./requirements-build.txt", "/tmp/requirements/"]
